version: '3.3'
services:
  jupyter:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    image: "guti1/drlnd"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
      - .:/opt/project
    command: [ "sh", "-c",
               "NB_UID=`ls -nd /home/jovyan/work | cut -d ' ' -f 3` \
                NB_GID=`ls -nd /home/jovyan/work | cut -d ' ' -f 4`"]
  jupyter-gpu:
    build:
      context: ./Docker
      dockerfile: Dockerfile-GPU
    image: "guti1/drlnd-gpu"
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
      - .:/opt/project
    command: [ "sh", "-c",
               "NB_UID=`ls -nd /home/jovyan/work | cut -d ' ' -f 3` \
                NB_GID=`ls -nd /home/jovyan/work | cut -d ' ' -f 4`,
                 jupyter-lab --ip 0.0.0.0 --port 8888 --allow-root --LabApp.token=''"]
  debug:
    build:
      context: ./Docker
      dockerfile: Dockerfile-debug
    image: "guti1/drlnd-debug"
    volumes:
      - .:/opt/project
    command: [ "sh", "-c", "/usr/local/bin/startup_script.sh"]
